"""empty message

Revision ID: c10af0cf9186
Revises: 
Create Date: 2019-01-19 11:24:09.542509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10af0cf9186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_contribution', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_contribution', 'tbl_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_contribution', type_='foreignkey')
    op.drop_column('tbl_contribution', 'group_id')
    # ### end Alembic commands ###
